### ISSUE TITLE
Issues installing this package with React version >= 17

### ISSUE THREAD

**Issue by SXV357** [uiwjs/react-split#145]
Every time I try installing split, I have to resort to using --force or --legacy-peer-deps and because of that I'm unable to deploy my project. Is there a specific version that works with react 17 or 18 so I can try using that instead?

**Comment by jaywcjlove** [comment]
@SXV357 https://github.com/uiwjs/react-split/blob/3cfa534f31e4a4d8cb0fed80cccc1a83e820585b/package.json#L38-L41

I cannot reproduce your problem.

**Comment by SXV357** [comment]
I actually figured out a way to get around this. I updated my react version, deleted a few extra dependencies and it worked
